--[[
    ╔══════════════════════════════════════════════════════════════════════════════╗
    ║ 🐺 LXR-SPIRITS :: RSG ITEM REGISTRATION                                   ║
    ║ wolves.land — The Land of Wolves | The Lux Empire | iBoss21               ║
    ║ Resource identity is locked to: lxr-spirits                                ║
    ╚══════════════════════════════════════════════════════════════════════════════╝
]]

-----------------------------------------------
-- lxr-spirits ritual items
-- Add inside: rsg-core/shared/items.lua
-- Do not duplicate hunting parts already present on your server.
-----------------------------------------------

ritual_sage_bundle = { name = 'ritual_sage_bundle', label = 'Ritual Sage Bundle', weight = 100, type = 'item', image = 'ritual_sage_bundle.png', unique = false, useable = true, shouldClose = true, description = 'A sacred sage bundle burned during ancestral spirit rituals.' },
dream_root         = { name = 'dream_root',         label = 'Dream Root',         weight = 80,  type = 'item', image = 'dream_root.png',         unique = false, useable = true, shouldClose = true, description = 'A bitter root used to open the mind during spirit visions.' },
blessed_water      = { name = 'blessed_water',      label = 'Blessed Water',      weight = 120, type = 'item', image = 'blessed_water.png',      unique = false, useable = true, shouldClose = true, description = 'Water prepared for cleansing rites and sacred ceremonies.' },
moon_water         = { name = 'moon_water',         label = 'Moon Water',         weight = 120, type = 'item', image = 'moon_water.png',         unique = false, useable = true, shouldClose = true, description = 'Water left under moonlight and used in spiritual cleansing.' },
spirit_token       = { name = 'spirit_token',       label = 'Spirit Token',       weight = 50,  type = 'item', image = 'spirit_token.png',       unique = false, useable = true, shouldClose = true, description = 'A small token used to strengthen a bond with a spirit guide.' },
spirit_ash         = { name = 'spirit_ash',         label = 'Spirit Ash',         weight = 20,  type = 'item', image = 'spirit_ash.png',         unique = false, useable = true, shouldClose = true, description = 'Fine ash left after ritual fire, kept for omens and offerings.' },
spirit_candle      = { name = 'spirit_candle',      label = 'Spirit Candle',      weight = 70,  type = 'item', image = 'spirit_candle.png',      unique = false, useable = true, shouldClose = true, description = 'A candle used to mark sacred ground during rituals.' },
ancestral_totem    = { name = 'ancestral_totem',    label = 'Ancestral Totem',    weight = 250, type = 'item', image = 'ancestral_totem.png',    unique = false, useable = true, shouldClose = true, description = 'A carved totem used in deep ancestral ceremonies.' },
ritual_bone_charm  = { name = 'ritual_bone_charm',  label = 'Ritual Bone Charm',  weight = 90,  type = 'item', image = 'ritual_bone_charm.png',  unique = false, useable = true, shouldClose = true, description = 'A carved bone charm used to focus spirit-bond rituals.' },
ritual_spirit_bowl = { name = 'ritual_spirit_bowl', label = 'Ritual Spirit Bowl', weight = 150, type = 'item', image = 'ritual_spirit_bowl.png', unique = false, useable = true, shouldClose = true, description = 'A ceremonial bowl used to hold offerings for spirit rituals.' },
-- Legendary animal offerings — obtained by hunting legendary animals in sacred lands
legendary_wolf_heart          = { name = 'legendary_wolf_heart',          label = 'Legendary Wolf Heart',          weight = 180, type = 'item', image = 'legendary_wolf_heart.png',          unique = false, useable = false, shouldClose = false, description = 'The still-warm heart of a legendary wolf. A sacred offering.' },
legendary_wolf_fang           = { name = 'legendary_wolf_fang',           label = 'Legendary Wolf Fang',           weight = 60,  type = 'item', image = 'legendary_wolf_fang.png',           unique = false, useable = false, shouldClose = false, description = 'A great fang taken from a legendary wolf.' },
legendary_eagle_heart         = { name = 'legendary_eagle_heart',         label = 'Legendary Eagle Heart',         weight = 120, type = 'item', image = 'legendary_eagle_heart.png',         unique = false, useable = false, shouldClose = false, description = 'A small but powerful heart of a legendary eagle.' },
legendary_eagle_feather_prime = { name = 'legendary_eagle_feather_prime', label = 'Legendary Eagle Feather',       weight = 30,  type = 'item', image = 'legendary_eagle_feather_prime.png', unique = false, useable = false, shouldClose = false, description = 'A prime flight feather from a legendary eagle.' },
legendary_bear_heart          = { name = 'legendary_bear_heart',          label = 'Legendary Bear Heart',          weight = 350, type = 'item', image = 'legendary_bear_heart.png',          unique = false, useable = false, shouldClose = false, description = 'The massive heart of a legendary bear. Prized for sacred rites.' },
legendary_bear_claw_prime     = { name = 'legendary_bear_claw_prime',     label = 'Legendary Bear Claw',           weight = 90,  type = 'item', image = 'legendary_bear_claw_prime.png',     unique = false, useable = false, shouldClose = false, description = 'A prime claw from a legendary bear.' },
legendary_cougar_heart        = { name = 'legendary_cougar_heart',        label = 'Legendary Cougar Heart',        weight = 160, type = 'item', image = 'legendary_cougar_heart.png',        unique = false, useable = false, shouldClose = false, description = 'The heart of a legendary cougar, still warm.' },
legendary_cougar_fang         = { name = 'legendary_cougar_fang',         label = 'Legendary Cougar Fang',         weight = 55,  type = 'item', image = 'legendary_cougar_fang.png',         unique = false, useable = false, shouldClose = false, description = 'A razor-sharp fang from a legendary cougar.' },
legendary_bison_heart         = { name = 'legendary_bison_heart',         label = 'Legendary Bison Heart',         weight = 500, type = 'item', image = 'legendary_bison_heart.png',         unique = false, useable = false, shouldClose = false, description = 'The enormous heart of a legendary bison. An ancient offering.' },
legendary_bison_horn          = { name = 'legendary_bison_horn',          label = 'Legendary Bison Horn',          weight = 400, type = 'item', image = 'legendary_bison_horn.png',          unique = false, useable = false, shouldClose = false, description = 'A great horn carved from a legendary bison.' },
legendary_elk_heart           = { name = 'legendary_elk_heart',           label = 'Legendary Elk Heart',           weight = 280, type = 'item', image = 'legendary_elk_heart.png',           unique = false, useable = false, shouldClose = false, description = 'The noble heart of a legendary elk.' },
legendary_elk_antler_prime    = { name = 'legendary_elk_antler_prime',    label = 'Legendary Elk Antler',          weight = 350, type = 'item', image = 'legendary_elk_antler_prime.png',    unique = false, useable = false, shouldClose = false, description = 'A prime antler from a legendary elk.' },
legendary_coyote_heart        = { name = 'legendary_coyote_heart',        label = 'Legendary Coyote Heart',        weight = 130, type = 'item', image = 'legendary_coyote_heart.png',        unique = false, useable = false, shouldClose = false, description = 'The cunning heart of a legendary coyote.' },
legendary_fox_tail_prime      = { name = 'legendary_fox_tail_prime',      label = 'Legendary Fox Tail',            weight = 70,  type = 'item', image = 'legendary_fox_tail_prime.png',      unique = false, useable = false, shouldClose = false, description = 'A prime tail from a legendary fox.' },
legendary_owl_feather_prime   = { name = 'legendary_owl_feather_prime',   label = 'Legendary Owl Feather',         weight = 25,  type = 'item', image = 'legendary_owl_feather_prime.png',   unique = false, useable = false, shouldClose = false, description = 'A feather of silence from a legendary owl.' },
legendary_deer_heart          = { name = 'legendary_deer_heart',          label = 'Legendary Deer Heart',          weight = 140, type = 'item', image = 'legendary_deer_heart.png',          unique = false, useable = false, shouldClose = false, description = 'The pure heart of a legendary white deer.' },
legendary_raven_wing          = { name = 'legendary_raven_wing',          label = 'Legendary Raven Wing',          weight = 45,  type = 'item', image = 'legendary_raven_wing.png',          unique = false, useable = false, shouldClose = false, description = 'A dark wing plucked from a legendary raven.' },
